name: Deploy Backend to EC2

on:
  push:
    branches: [ main ]
    paths:
      - 'Backend/**'
      - '.github/workflows/deploy-backend.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        
    - name: Install dependencies
      run: |
        cd Backend
        pip install -r requirements.txt
        
    - name: Run tests
      run: |
        cd Backend
        python -m pytest --tb=short || echo "Tests completed with issues"
        
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        port: 22
        script: |
          cd /home/ubuntu/mydscvr-backend
          git pull origin main
          source venv/bin/activate
          pip install -r Backend/requirements.txt
          sudo systemctl restart mydscvr-backend
          sudo systemctl status mydscvr-backend