name: Sync DataCollection to Dedicated Repository

on:
  push:
    branches: [ main ]
    paths:
      - 'DataCollection/**'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout main repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        
    - name: Setup Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        
    - name: Clone DataCollection repository
      run: |
        git clone https://github.com/saleemjadallah/mydscvr.datacollection.git datacollection-repo
        
    - name: Sync DataCollection folder
      run: |
        # Remove old DataCollection contents (except .git)
        cd datacollection-repo
        find . -mindepth 1 -not -path './.git*' -delete
        
        # Copy new DataCollection contents
        cp -r ../DataCollection/* .
        
        # Add all changes
        git add .
        
        # Check if there are changes to commit
        if ! git diff --cached --quiet; then
          git commit -m "🔄 Sync DataCollection from main repository
          
          Automated sync of DataCollection folder from main DXB-events repository.
          Commit: ${{ github.sha }}
          "
          
          # Push to the DataCollection repository
          git push https://${{ secrets.GITHUB_TOKEN }}@github.com/saleemjadallah/mydscvr.datacollection.git main
          
          echo "✅ Successfully synced DataCollection to dedicated repository"
          
          # Trigger deployment on the dedicated repository
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/saleemjadallah/mydscvr.datacollection/actions/workflows/deploy-datacollection.yml/dispatches \
            -d '{"ref":"main"}' || echo "⚠️ Could not trigger deployment - workflow may not exist in dedicated repo"
        else
          echo "ℹ️ No changes to sync"
        fi 